[package]
name = "lan-qr-address"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.26", features = ["derive"] }
local-ip-address = "0.4.9"
qr2term = "0.3.1"
